# Generated by Django 5.2.4 on 2025-07-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('Helltide', 'Helltide'), ('Dungeon', 'Dungeon'), ('World Boss', 'World Boss')], max_length=50)),
                ('mythics_dropped', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField()),
                ('crit_chance', models.FloatField()),
                ('crit_damage', models.FloatField()),
                ('attack_speed', models.FloatField()),
                ('lightning_damage', models.FloatField()),
                ('skill_ranks', models.IntegerField()),
                ('paragon_points', models.IntegerField()),
                ('fun_score', models.IntegerField()),
                ('session_length', models.FloatField()),
                ('estimated_dps', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
