# Generated by Django 5.2.4 on 2025-07-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('session_length', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('activity_type', models.CharField(choices=[('', 'Select Activity'), ('helltide', 'Helltide'), ('nightmare_dungeon', 'Nightmare Dungeon'), ('world_boss', 'World Boss'), ('seasonal_realm', 'Seasonal Realm'), ('pit_of_artificers', 'Pit of the Artificers')], default='', help_text='Select from dropdown', max_length=50)),
                ('mythics_dropped', models.PositiveIntegerField(default=0, help_text='Number of Mythics dropped')),
                ('skill_ranks', models.PositiveIntegerField(help_text='Total rank of Lightning skills')),
                ('intelligence', models.PositiveIntegerField(help_text='Intelligence stat')),
                ('lightning_damage', models.PositiveIntegerField(help_text='Lightning damage bonus')),
                ('attack_speed', models.FloatField(help_text='Attacks per second')),
                ('crit_chance', models.FloatField(help_text='Critical hit chance (%)')),
                ('crit_damage', models.FloatField(help_text='Critical damage bonus (%)')),
                ('paragon_points', models.PositiveIntegerField(help_text='Current Paragon level')),
                ('fun_score', models.PositiveIntegerField(help_text='Fun rating (1-10)')),
                ('estimated_dps', models.FloatField(blank=True, help_text='Calculated DPS', null=True)),
            ],
        ),
    ]
